// Generated by Haxe 4.3.0-rc.1+
#include <hxcpp.h>

#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_haxe_iterators_ArrayIterator
#include <haxe/iterators/ArrayIterator.h>
#endif
#ifndef INCLUDED_doudecimal_Doudecimal_
#include <doudecimal/Doudecimal_.h>
#endif
#ifndef INCLUDED_doudecimal__Doudecimal_Doudecimal_Impl_
#include <doudecimal/_Doudecimal/Doudecimal_Impl_.h>
#endif
#ifndef INCLUDED_Type
#include <Type.h>
#endif
#ifndef INCLUDED__Test_Test_Fields_
#include <_Test/Test_Fields_.h>
#endif
#ifndef INCLUDED_StringTools
#include <StringTools.h>
#endif
#ifndef INCLUDED_StringBuf
#include <StringBuf.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif

void __files__boot();

void __boot_all()
{
__files__boot();
::hx::RegisterResources( ::hx::GetResources() );
::haxe::Log_obj::__register();
::haxe::iterators::ArrayIterator_obj::__register();
::doudecimal::Doudecimal__obj::__register();
::doudecimal::_Doudecimal::Doudecimal_Impl__obj::__register();
::Type_obj::__register();
::_Test::Test_Fields__obj::__register();
::StringTools_obj::__register();
::StringBuf_obj::__register();
::Std_obj::__register();
::haxe::Log_obj::__boot();
}

