// Generated by Haxe 4.3.0-rc.1+
#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"/home/nanjizal/haxe/versions/779b005/std/StringTools.hx",
"/home/nanjizal/haxe/versions/779b005/std/cpp/_std/Std.hx",
"/home/nanjizal/haxe/versions/779b005/std/cpp/_std/StringBuf.hx",
"/home/nanjizal/haxe/versions/779b005/std/cpp/_std/Type.hx",
"/home/nanjizal/haxe/versions/779b005/std/cpp/_std/haxe/Log.hx",
"/home/nanjizal/haxe/versions/779b005/std/haxe/iterators/ArrayIterator.hx",
"?",
"Test.hx",
"doudecimal/Doudecimal.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"/home/nanjizal/haxe/versions/779b005/std/StringTools.hx",
"/home/nanjizal/haxe/versions/779b005/std/cpp/_std/Std.hx",
"/home/nanjizal/haxe/versions/779b005/std/cpp/_std/StringBuf.hx",
"/home/nanjizal/haxe/versions/779b005/std/cpp/_std/Type.hx",
"/home/nanjizal/haxe/versions/779b005/std/cpp/_std/haxe/Log.hx",
"/home/nanjizal/haxe/versions/779b005/std/haxe/iterators/ArrayIterator.hx",
"/home/nanjizal/haxey/doudecimal/Doudecimal/demo/?",
"/home/nanjizal/haxey/doudecimal/Doudecimal/demo/Test.hx",
"/home/nanjizal/haxey/doudecimal/Doudecimal/src/doudecimal/Doudecimal.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"Std",
"StringBuf",
"StringTools",
"_Test.Test_Fields_",
"Type",
"doudecimal._Doudecimal.Doudecimal_Impl_",
"doudecimal.Doudecimal_",
"haxe.Log",
"haxe.iterators.ArrayIterator",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(::hx::__hxcpp_all_classes, ::hx::__hxcpp_all_files_fullpath); }
