// Generated by Haxe 4.3.0-rc.1+
#ifndef INCLUDED_doudecimal__Doudecimal_Doudecimal_Impl_
#define INCLUDED_doudecimal__Doudecimal_Doudecimal_Impl_

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(doudecimal,_Doudecimal,Doudecimal_Impl_)

namespace doudecimal{
namespace _Doudecimal{


class HXCPP_CLASS_ATTRIBUTES Doudecimal_Impl__obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Doudecimal_Impl__obj OBJ_;
		Doudecimal_Impl__obj();

	public:
		enum { _hx_ClassId = 0x4db77126 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="doudecimal._Doudecimal.Doudecimal_Impl_")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"doudecimal._Doudecimal.Doudecimal_Impl_"); }

		inline static ::hx::ObjectPtr< Doudecimal_Impl__obj > __new() {
			::hx::ObjectPtr< Doudecimal_Impl__obj > __this = new Doudecimal_Impl__obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< Doudecimal_Impl__obj > __alloc(::hx::Ctx *_hx_ctx) {
			Doudecimal_Impl__obj *__this = (Doudecimal_Impl__obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Doudecimal_Impl__obj), false, "doudecimal._Doudecimal.Doudecimal_Impl_"));
			*(void **)__this = Doudecimal_Impl__obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~Doudecimal_Impl__obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Doudecimal_Impl_",47,7f,e0,b3); }

		static int _new(int v);
		static ::Dynamic _new_dyn();

		static ::String toString(int this1);
		static ::Dynamic toString_dyn();

		static int fromString(::String s);
		static ::Dynamic fromString_dyn();

};

} // end namespace doudecimal
} // end namespace _Doudecimal

#endif /* INCLUDED_doudecimal__Doudecimal_Doudecimal_Impl_ */ 
